/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package rps.game.backend;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        RockPaperScissors rps = new RockPaperScissors();
        Scanner scanner = new Scanner(System.in);
        System.out.print("Player 1, please make your choice(Rock, Paper, Scissors): ");
        String playerOne = scanner.nextLine();
        String playerTwo = rps.randomDecision();

        System.out.println(rps.rockPaperScissors(playerOne, playerTwo));
    }
}
