/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package rps.game.backend;

import rps.game.backend.database.DatabaseConnector;
import rps.game.backend.database.InsertIntoDatabase;
import rps.game.backend.gameList.GameManager;
import rps.game.backend.web.CorsHandler;
import rps.game.backend.web.WebServer;

import java.sql.Connection;

public class Main {

    public static void main(String[] args) throws Exception{
        RockPaperScissors rockPaperScissors = new RockPaperScissors();
        GameManager gameManager = new GameManager();
        CorsHandler corsHandler = new CorsHandler();

        String database_url = System.getenv("DATABASE_URL");
        String host = database_url.substring(91, 132);
        String database = database_url.substring(138, 152);
        String user = database_url.substring(11, 25);
        String password = database_url.substring(26, 90);

        DatabaseConnector databaseConnector = new DatabaseConnector(host, database, user, password);
        Connection connection = databaseConnector.connect();

        InsertIntoDatabase insertIntoDatabase = new InsertIntoDatabase(connection);

        new WebServer(rockPaperScissors, gameManager, insertIntoDatabase, corsHandler).startServer();
    }
}
