/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package rps.game.backend;

import rps.game.backend.gameList.GameManager;
import rps.game.backend.web.CorsHandler;
import rps.game.backend.web.WebServer;

import java.util.Scanner;

public class Main {

    public static void main(String[] args) throws Exception{
        RockPaperScissors rockPaperScissors = new RockPaperScissors();
        GameManager gameManager = new GameManager();
        CorsHandler corsHandler = new CorsHandler();

        new WebServer(rockPaperScissors, gameManager, corsHandler).startServer();
//        Scanner scanner = new Scanner(System.in);
//        System.out.print("Player 1, please make your choice(Rock, Paper, Scissors): ");
//        String playerOne = scanner.nextLine();
//        String playerTwo = rps.randomDecision();
//
//        System.out.println(rps.rockPaperScissors(playerOne, playerTwo));
    }
}
